name: Terraform CI Check

on: pull_request

jobs:
  ci-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
    - name: Run TFLint
      run: docker run --rm -v $(pwd):/data -t ghcr.io/terraform-linters/tflint
    - name: Run Trivy
      run: docker run --rm -v $(pwd):/src -w /src -t aquasec/trivy fs .
    - name: Run Terraform-docs
      run: docker run --rm -v "$(pwd):/src" -u $(id -u) quay.io/terraform-docs/terraform-docs /src
    - name: Check README.md diff by Terraform-docs
      run: |
        if [[ $(git diff --name-only | grep README.md) ]]; then
          echo "There's README.md diff."
          exit 1
        fi
    - uses: hashicorp/setup-terraform@v3
    - name: Terraform init
      run: terraform init
    - name: Terraform fmt
      run: terraform fmt -check
    - name: Terraform validate
      run: terraform validate
